"""empty message

Revision ID: 286f2306f162
Revises: be7cd596e94b
Create Date: 2022-05-16 17:30:45.029995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286f2306f162'
down_revision = 'be7cd596e94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo__question', schema=None) as batch_op:
        batch_op.alter_column('memo_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.alter_column('memo_content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo__question', schema=None) as batch_op:
        batch_op.alter_column('memo_content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('memo_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
