"""empty message

Revision ID: 4c737090379c
Revises: bfcbc9412797
Create Date: 2022-05-23 18:12:02.170764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c737090379c'
down_revision = 'bfcbc9412797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gomin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_gomin_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gomin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_gomin_user_id_user'), type_='foreignkey')
        batch_op.drop_column('modify_date')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
