"""empty message

Revision ID: 8279b2042409
Revises: 9a1f32422af5
Create Date: 2022-05-16 11:25:08.570386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8279b2042409'
down_revision = '9a1f32422af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memo__question',
    sa.Column('memo_id', sa.Integer(), nullable=False),
    sa.Column('memo_subject', sa.String(length=200), nullable=False),
    sa.Column('memo_content', sa.Text(), nullable=False),
    sa.Column('memo_create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('memo_id', name=op.f('pk_memo__question'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memo__question')
    # ### end Alembic commands ###
