"""empty message

Revision ID: be7cd596e94b
Revises: bebcb05f471a
Create Date: 2022-05-16 13:31:38.331066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7cd596e94b'
down_revision = 'bebcb05f471a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo__question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo_create_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo__question', schema=None) as batch_op:
        batch_op.drop_column('memo_create_date')

    # ### end Alembic commands ###
