"""empty message

Revision ID: bebcb05f471a
Revises: 73bf02535680
Create Date: 2022-05-16 13:27:59.279255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebcb05f471a'
down_revision = '73bf02535680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo__question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo__question', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
