"""empty message

Revision ID: bfcbc9412797
Revises: 30c902e04851
Create Date: 2022-05-23 17:15:20.199400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcbc9412797'
down_revision = '30c902e04851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gomin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gomin'))
    )
    op.create_table('gomin__answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gomin_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gomin_id'], ['gomin.id'], name=op.f('fk_gomin__answer_gomin_id_gomin'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gomin__answer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gomin__answer')
    op.drop_table('gomin')
    # ### end Alembic commands ###
