"""empty message

Revision ID: cbc18aa4b116
Revises: 286f2306f162
Create Date: 2022-05-16 19:31:30.782168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc18aa4b116'
down_revision = '286f2306f162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo__question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.drop_column('memo_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo__question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo_content', sa.TEXT(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
