"""empty message

Revision ID: cff85af477c5
Revises: 6cebdbb2dfcd
Create Date: 2022-05-23 19:03:58.302531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff85af477c5'
down_revision = '6cebdbb2dfcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gomin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_gomin_id_gomin'), 'gomin', ['gomin_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_gomin_id_gomin'), type_='foreignkey')
        batch_op.drop_column('gomin_id')

    # ### end Alembic commands ###
