"""empty message

Revision ID: f51e084cf8a8
Revises: cbd2359b2677
Create Date: 2022-05-23 18:49:43.653377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51e084cf8a8'
down_revision = 'cbd2359b2677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gomin_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gomin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gomin_id'], ['gomin.id'], name=op.f('fk_gomin_voter_gomin_id_gomin'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_gomin_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'gomin_id', name=op.f('pk_gomin_voter'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gomin_voter')
    # ### end Alembic commands ###
